Try using HTTP gateways if IPFS get fails
propensive/fury-old pull request #1108
Opened 2020-02-28 13:04 UTC by odisseus

2020-02-29 10:47 UTC, propensive requested changes

2020-02-29 10:47 UTC, propensive commented on src/core/external.scala
> +  private val knownGateways = List(
Good to build in some sort of choice. I'd like to make this configurable, but only once I've done a small overhaul of the configuration interface. (Issue #900)

2020-02-29 10:47 UTC, propensive commented on src/core/external.scala
> +        val gateway = Random.shuffle(knownGateways).head
I think that determinism would be better, though I also get the idea that building a tool which builds in a third-party service without a SLA isn't a good idea. But we will make it configurable.

2020-02-29 10:47 UTC, propensive commented on src/core/external.scala
> +        log.warn(s"Trying $gateway")
Use `info` instead of `warn`.

2020-02-29 10:47 UTC, propensive commented on src/core/external.scala
> +        data <- Http.get(Https(Path(gateway) / "api" / "v0" / s"get?arg=${hash.toBase58}&archive=true"), Map(), Set.empty)
Is this URL better than `https://<gateway>/ipfs/<hash>`? It avoids directories being displayed through an HTML web interface, right?

2020-02-29 15:49 UTC, odisseus commented on src/core/external.scala
> +        val gateway = Random.shuffle(knownGateways).head
I don't want all the users to hit the same gateway all the time, so I think it is better to choose one at random. On the other hand, this feature is going to be used very rarely (I hope), and it should not make any significant impact on any gateway.

2020-02-29 15:51 UTC, odisseus commented on src/core/external.scala
> +        log.warn(s"Trying $gateway")
This state is an error, although a recoverable one. Therefore, I think the warn level is appropriate here.

2020-02-29 15:56 UTC, odisseus commented on src/core/external.scala
> +        data <- Http.get(Https(Path(gateway) / "api" / "v0" / s"get?arg=${hash.toBase58}&archive=true"), Map(), Set.empty)
This is [part](https://docs.ipfs.io/reference/api/http/#api-v0-get) of the standard HTTP interface of an IPFS node. This particular endpoint allows to download a directory as a single TAR file.

2020-02-29 16:03 UTC, odisseus commented on src/core/external.scala
> +  private val knownGateways = List(
Does the configuration format support lists of values?

2020-03-02 18:49 UTC, odisseus commented on src/core/external.scala
> +  private val knownGateways = List(
See #1115.

2020-03-02 18:49 UTC, odisseus commented on src/core/external.scala
> +        val gateway = Random.shuffle(knownGateways).head
The shuffling has been removed.

2020-03-02 18:50 UTC, odisseus commented on src/core/external.scala
> +        log.warn(s"Trying $gateway")
Done

2020-03-03 02:58 UTC, propensive requested changes
I think we need something extra in the logic for when to use HTTP and when to use IPFS:
- if the user has IPFS installed on the `PATH` or a Fury-managed installation, use it, falling back to HTTP if the request times out
- if not, and the user is doing an IPFS `add` operation, install IPFS into order to perform the operation
- if not, use the HTTP gateway without installing IPFS.

In other words: use IPFS if we have it, install it only if we need it, otherwise use HTTP, and use HTTP if IPFS times out.

2020-03-03 02:58 UTC, propensive commented on src/core/external.scala
> +  private val knownGateways = List(
Yes, it does. We have an OGDL [de]serializer for `List[T]`.

2020-03-03 02:58 UTC, propensive commented on src/core/external.scala
> +      val query = Query & "arg" -> hash.toBase58 & "archive" -> "true"
Whilst the syntax for `Query` is novel, I think I would prefer something more similar to a `ListMap`, i.e. an ordered map. My main concern is the introduction of `&` as an operator. It needs to have weaker precedence than `->` in order to work, and this isn't so clear. I think it would make sense to write this as, `Query("arg" -> hash.toBase58, "archive" -> "true")` or `Query(ListMap("arg" -> hash.toBase58, "archive" -> "true"))`.

2020-03-03 02:58 UTC, propensive commented on src/core/external.scala
> +    private[this] def getFile(hash: Multihash, path: Path): Try[Path] = for {
There needs to be a timeout on here, otherwise it will never terminate and will never fall back to using HTTP.

2020-03-03 10:27 UTC, odisseus commented on src/core/external.scala
> +    private[this] def getFile(hash: Multihash, path: Path): Try[Path] = for {
That's a good point, but I'd rather do it in another pull request.

2020-03-03 10:40 UTC, odisseus commented
Regarding the usage of IPFS gateways vs setting up a local node, I think the local node should be used as much as possible. This will avoid the strain on the gateways and make the user independent of them. There is even an [opinion](https://medium.com/pinata/the-ipfs-gateway-problem-64bbe7eb8170) that public gateways do a disservice to the IPFS community.

2020-03-03 13:21 UTC, odisseus commented on src/core/external.scala
> +      val query = Query & "arg" -> hash.toBase58 & "archive" -> "true"
The current syntax allows adding more parentheses to make the priority of operations more clear:
```
val query1 = Query & ("arg" -> hash.toBase58) & ("archive" -> "true")
val query2 = Query & ("arg", hash.toBase58) & ("archive", "true")
```

2020-03-03 13:34 UTC, odisseus commented on src/core/external.scala
> +    private[this] def getFile(hash: Multihash, path: Path): Try[Path] = for {
See #1116.

2020-03-03 14:29 UTC, merged

2020-03-03 17:08 UTC, propensive commented
> Regarding the usage of IPFS gateways vs setting up a local node, I think the local node should be used as much as possible. This will avoid the strain on the gateways and make the user independent of them. There is even an [opinion](https://medium.com/pinata/the-ipfs-gateway-problem-64bbe7eb8170) that public gateways do a disservice to the IPFS community.

Yes, I would rather use the node if we can. But if it's a choice between downloading a 10K file over HTTP and a large download of IPFS, which might not work due to network restrictions, then I would rather download with HTTP.