Revert "Fixed errors thrown during tab-completions in `cli.preview` (#1223)"
propensive/fury-old pull request #1265
Opened 2020-04-14 19:31 UTC by odisseus

This reverts commit 1ba336e47a26782370f75d4625f54f75e250ad52, which caused the issue #1088 to reappear.

2020-04-14 23:42 UTC, propensive reviewed
I don't remember the details of the original change, though there were certain tab-completions that would fail, printing unwanted error output to STDOUT, which could not be interpreted by the completions system.

2020-04-15 02:36 UTC, odisseus commented
I have found a way to solve those problems. I have updated just a couple commands so far, but I'll refactor all of them if my solution works well.

2020-04-15 19:55 UTC, propensive requested changes
Thanks for working on this. I think we need to try to reduce the amount of code we have here. I think that certainly some of the logic could be factored into methods on one of our model objects. I don't want to mix up front-end code (e.g. things like `cli` and `ModuleArg`) with backend code, but we could have a method on `Layer` which gets the current module/project. Something like this:
```
def moduleRef(project: Option[ProjectId] = None, module: Option[ModuleId] = None): Try[ModuleRef] 
```
This won't be the whole story, of course, but I think there's a lot of improvement to be made here.

2020-04-16 01:52 UTC, odisseus commented
The actual problem lies not in the repetitive code, but in the fact that the same code must handle bad arguments in two different ways. 

When the command completion is constructed, we want to hide any exceptions and substitute failures with nil values (usually `None` or empty list) so that the completion hints can be constructed further. 

When the command is actually executed, we want to interrupt execution on the first failure, and produce a descriptive message about the nature of the failure.

As a consequence, each potential failure to resolve a value against the context built by the previous steps (e. g. project depending on the layer, module depending on the project) must be both substituted and stored. This is the reason why the code that resolves e. g. the project cannot be inlined into the main for-comprehension, even though it returns a `Try`.

I agree that the code which handles the commands is quite repetitive, and it must be possible to extract common idioms (such as getting a valid `ModuleRef`). However, cleaning up the CLI is a huge chunk of work that lies outside the scope of this pull request. My goal here is just resolving the contradiction between #1088 and #1222. Besides, repetitive as it is, I believe my code is slightly better and clearer than in the master.

2020-04-16 15:27 UTC, propensive commented
Yes, I agree there. I've got quite a lot of ideas for fixing that code which will have to wait until after the next release. So I can either merge this now, or wait for you to replicate the fixes elsewhere. Please go ahead and merge when ready!

2020-04-16 15:55 UTC, merged