added sorted reported
propensive/fury-old pull request #1361
Opened 2020-05-09 06:47 UTC by astefanich

Added a "stable" reporter, which displays compile results in sorted order according to module name. "Sorted" felt like a more appropriate name than stable. Test added to the integration suite.

resolves #1351

2020-05-09 19:51 UTC, propensive requested changes
Great to see this PR in the queue, @astefanich! There are a load of comments, but don't be too discouraged by them—I'm just particularly attentive to first-time contributors, and I'm really happy to see the contribution. There should be no problem merging it with the changes. ;)

2020-05-09 19:51 UTC, propensive commented on src/core/reporter.scala
> +object SortedLinearReporter extends LinearReporter("sorted") {
Can we call it `summary`?

2020-05-09 19:51 UTC, propensive commented on src/core/reporter.scala
> +  type MCE = ModuleCompileEvent
Not to criticize this in general, but (for better or worse) we don't use any abbreviations anywhere in the code, so I'd like to keep that consistent. Can you delete these lines and write these types out in full?

2020-05-09 19:51 UTC, propensive commented on src/core/reporter.scala
> +    val interleaver = new Interleaver(3000L)
This, I think, is an experiment which became redundant, so unless it's referred to anywhere, I think we can just get rid of this line.

2020-05-09 19:51 UTC, propensive commented on test/passing/sorted-report/check
> +Successfully compiled module test-project/module-e
So, the summary message I would like to see would just be a single line:
```
Successfully compiled test-project/module-a, test-project/module-b, test-project/module-c, test-project/module-d, test-project.module-e
```
```

2020-05-09 19:51 UTC, propensive commented on test/passing/sorted-report/script
> +echo "object ModuleE{ val eVal = 'E' }" > src/module-e/ModuleE.scala
If it's easier (too late now, I guess...) we can just create these `.scala` files in the test directory.

2020-05-09 19:51 UTC, propensive commented on src/core/reporter.scala
> +  val all: List[Reporter] = List(GraphReporter, InterleavingReporter, UnsortedLinearReporter, SortedLinearReporter, QuietReporter)
Rename these (back) to `LinearReporter` and `SummaryReporter`.

2020-05-09 19:51 UTC, propensive commented on src/core/reporter.scala
> +    val (started, stopped, otherEvts) = (PQ[MCE]()(moduleOrd), PQ[MCE]()(moduleOrd), PQ[MCE]()(moduleOrd))
I think all we need here is a `mutable.Set[ModuleRef]` which collects the modules when they're complete.

2020-05-09 19:51 UTC, propensive commented on src/core/reporter.scala
> +      case d: DiagnosticMsg => otherEvts enqueue d
So, I would a) ignore `StartCompile` messages, b) record `StopCompile` module refs in the set, and c) probably record whether any `DiagnosticMsg` events are received, and `log.note` them instead of `log.info` when they happen. This way, they will appear in the global log, but won't pollute the output if they arrive in a slightly different order sometimes.

2020-05-09 19:51 UTC, propensive commented on src/core/reporter.scala
> +    }
I'm not sure I understand what this is doing... but I don't think we need it anyway. ;)

2020-05-09 19:51 UTC, propensive commented on src/core/reporter.scala
> +abstract class LinearReporter(name: String) extends Reporter(name){
I *think* (but will trust your judgement) after the changes below, that extracting out the abstract interface isn't worth it. I don't think the extra layer will give us much deduplication of code.

2020-05-09 22:51 UTC, astefanich commented
I set up main.yml to run on my fork. It took a couple of tries for them all to pass, as something random seemed to fail every time, even without me editing anything. Is this to be expected?

2020-05-10 01:37 UTC, propensive commented
Yes, there are "random failures" more often than I'd like, but I hope that this PR will fix some of them! Did you happen to notice if the failures looked "significant"? We often see log messages appearing in a slightly different order, and sometimes the "Starting BSP..." messages appear.

Doing an exact character-for-character check on the output is one reason these tests are such high-maintenance...

2020-05-10 01:56 UTC, propensive requested changes

2020-05-10 01:56 UTC, propensive commented on src/core/reporter.scala
> +      case StopCompile(ref, true) => moduleStrings += ref.id
We would avoid using `String`s for as long as possible, here. The reason comes a bit later...

2020-05-10 01:56 UTC, propensive commented on src/core/reporter.scala
> +    val moduleStrings = collection.mutable.TreeSet[String]()
Keep the type as `ModuleRef` and call it `moduleRefs`.

2020-05-10 01:56 UTC, propensive commented on src/core/reporter.scala
> +    log.info(summary.dropRight(2).toString)
We would never bother with anything so performance-conscious just for a log message. (FWIW, the `StringBuilder` is mutable anyway, so there's no need to fold over the reference to it—with this approach you could just use `foreach` on the `moduleStrings`.) The easy way would be to use `moduleStrings.mkString(", ")` and then you can avoid the `dropRight` on L78.

However, our `log.info` accepts `UserMsg` as input in addition to `String`. `UserMsg` provides rich colored output for terminals that support it (all of them these days). You can construct one with `msg"""Text in here with $substitutions."""`.

In this example, I can't remember if it works, but you could try substituting `moduleRefs.to[List]` in here. If it doesn't, you'll have to make them into a list. Try something like this:
```
moduleRefs.to[List].foldLeft(msg"") { case (ms, m) => msg"$ms, $m" }
```

2020-05-10 01:56 UTC, propensive commented on src/core/reporter.scala
> +    val moduleStrings = collection.mutable.TreeSet[String]()
`ModuleRef`s might have an `Ordering` instance, but if they don't just use a plain `mutable.Set` and sort later.

2020-05-10 01:56 UTC, propensive commented on test/passing/summary-report/check
> +Successfully compiled test-project/module-a, test-project/module-b, test-project/module-c, test-project/module-d, test-project/module-e
The tests always run with the `nocolor` reporter, so this shouldn't have to change once you start using `UserMsg`. If you have lost the colorful output, it's probably because the integration tests didn't clean up after themselves, and you'll need to run,
```
fury config set --theme full
```

2020-05-10 03:48 UTC, astefanich commented on src/core/reporter.scala
> +      case StopCompile(ref, true) => moduleStrings += ref.id
ah, I didn't realize notice that.

2020-05-10 05:57 UTC, astefanich commented
I re-ran the build file on my fork, and they passed after a few tries:
https://github.com/astefanich/fury/actions/runs/100410616

Since the tests are a little unpredictable, this is probably easier than making a new commit/PR every time I want to rerun.

2020-05-10 12:16 UTC, propensive commented
@odisseus is working on a fix for some of the test instability. I can usually check the error output before merging to check whether the test errors are real breakages or not, at least until we have more stability. One other alternative would be to run failed tests twice to see if they work the second time, but I think that just kicks the can down the road a bit...

2020-05-10 12:45 UTC, propensive commented
Ah, there's one more thing to do here... we should update most of the tests to use your sorted reporter! That would fix the one current test failure. :)

2020-05-10 21:27 UTC, propensive commented
Give me a nod when it's ready to merge, @astefanich!

2020-05-10 22:04 UTC, astefanich commented
ready sir

2020-05-11 13:35 UTC, merged

2020-05-11 13:35 UTC, propensive commented
Very happy to have this in Fury! Thank you @astefanich, especially given all the polishing I was asking for along the way...!