add locals jars/ validate binaries on import
propensive/fury-old pull request #1382
Opened 2020-05-12 20:43 UTC by astefanich

Added an option on 'fury binary add' to allow both remote and local jars. Both kinds are validated on initial import; local jars according to their absolute path.
Added a path attribute which prints in table, to denote where imported jars are save on host filesystem. 
Creating a new type to distinguish between remote and local jars ripped through client code and the type checker went AWOL, so I kept a single 'Binary' type.
#1350 
#544

2020-05-12 21:01 UTC, propensive commented
This sounds awesome, and I'm impressed you've managed to find your way around! I think @szymonrodziewicz was asking for this recently...

I haven't looked in detail yet, but can we have the JARs referred to using the same command syntax that we use for resources? There's a problem with absolute paths because it makes the builds non-portable, and there's a potential security issue with someone publishing a build with a reference to `/home/enemy/secrets.jar` and then doing something evil with it in an application module. Something similar to the way we specify resources would allow us to choose JAR files stored inside Git repos or inside the working directory.

I'll try to take a closer look tonight.

2020-05-12 21:13 UTC, astefanich commented
What if I simply copied the jar into something like .fury/.lib in the working directory, or perhaps a directory in ~/.cache/fury/bins. That way the absolute path is only used for initial validating/locating the file. Then on 'fury binary remove' it can be evicted. 

I haven't accounted for the git constraint yet. Is the validation simply checking that the jar is contained with any .git directory/subdirectory when its initially added?

2020-05-12 21:38 UTC, propensive requested changes
So, firstly, well done for managing to navigate around such a variety of different parts of the code!

The most important change needed will be find a precise representation of the binary. One possibility would be the following:
- restore `Binary` to its previous form
- add a `jarFiles` `SortedSet[JarFile]` to `Module` which accurately represents a JAR file which may be stored in a repository, or as a local file.
- introduce a common supertrait to `Binary` and `JarFile` so that in the places we need a common representation (e.g. the tabular list) we can just give it `binaries ++ jarFiles` and it will display the appropriate information for each.

I would like to reuse the representation of `Resource` if possible, but it might be easier to create new types. One possibility to explore would be to literally use `Resource`s in their current form. They exist only to included extra files in produced JAR files, but it would be a matter of a boolean flag to determine if they (as JAR files) should also be included on the compile classpath. I'm not sure this would be our ultimate solution, but I think it would get us closer.

Modifying the data that's stored in the layer files is tricky, by the way: adding new fields is generally safe, but removing or renaming any requires a new version number, and some short migration code to be written to ensure that layer files remain forwards-compatible.

Let me know if you need any more pointers, and thanks for persevering!

2020-05-12 21:38 UTC, propensive commented on src/core/args.scala
> +  val LocalJarFileArg = CliParam[JarFile]('l', 'local, "specify a local binary dependency")
Let's use `-f` and `--file` for this parameter, which is what we have done elsewhere.

2020-05-12 21:38 UTC, propensive commented on src/core/binary.scala
> +  implicit val pure = (s: String) => if(s.isEmpty) None else Some(s)
This gives up too much typesafety, unfortunately, and is generally not recommended. Can you delete this line and just wrap everything in `Some` where it's needed?

2020-05-12 21:38 UTC, propensive commented on src/core/binary.scala
> +  implicit val pure = (s: String) => if(s.isEmpty) None else Some(s)
Oh, also, in general implicits should *always* have an explicit return type.

2020-05-12 21:38 UTC, propensive commented on src/core/binary.scala
>    def spec = str"$group:$artifact:$version"
I think this will need to be cleaned up. The `NA` value isn't typesafe enough. I think there's a real risk of methods assuming that it's a reasonable value. I think that a more drastic redesign of the `Binary` type is necessary. In general, trying to maintain a not-quite-perfect representation of the model while the rest of the code is changing causes proliferation of bugs. So in general, a priority is put on making the model definitions an exact representation of only the states we want to represent, as it saves problems down the line, at the expense of a greater up-front cost.

2020-05-12 21:38 UTC, propensive commented on src/module/module.scala
> +    targetBin    <- call.exactlyOne(BinSpecArg, LocalJarFileArg)
Glad you found this method!

2020-05-12 21:38 UTC, propensive commented on src/model/ids.scala
> +  implicit val jarPath = (bin: JarFile) => Path(bin.path)
This implicit should be removed for the same reasons.

2020-05-12 21:38 UTC, propensive commented on test/passing/binary-validation/check
> +BSP server is listening for incoming connections
I think these three lines only appear if the test is run before Fury has started a BSP connection. They probably won't be shown if the test is run in CI.

2020-05-12 21:38 UTC, propensive commented on test/passing/binary-validation/description
> +and availability when they are added to a module.
This file was meant to be a one-liner, though I guess this just prints out three lines instead of one in the output... ;)

2020-05-12 21:38 UTC, propensive commented on test/passing/binary-validation/script
> +echo $?
This all looks pretty solid. It's not too important, but I'm hoping to make these test scripts shorter (and faster) by running the first few commands (let's say lines 1-7 in this file) in the test directory, deleting them from the script file, and then running a `fury layer commit` to add it to the Git repository. PR #1379 is a WIP example of this change.

2020-05-12 21:42 UTC, propensive commented
> What if I simply copied the jar into something like .fury/.lib in the working directory

I think this doesn't work in general. The build that gets run should always reflect the current state, so if that JAR file changes (especially if it's changed by Git), there should be no opportunity for it to accidentally keep using the old cached version.

2020-05-12 23:30 UTC, astefanich commented
What about hashing jar/files external to the layer to ipfs?

Most commands will display an absolute path if you give it one. Pretty much everything operates on a path relative to the layer. But if you reference a directory or a file that's outside the layer, the full path gets resolved and displayed in a 'list' command as well as on the build file in ipfs.

Its probably not an issue if you're referencing a directory, since it will look like this:
tmp/someSudDir//**

But if you add a file, namely a resource file or a jar, it gets displayed in full, with glob suffixed to the file.
tmp/someSudDir//sometext.txt//**

Since both resources and binaries paths need to concealed somehow,
maybe encrypt the path, create a separate ipfs hash for each resource external to the layer, or not displaying it at all?
 I think packaging a fat jar would remove the need to resolve paths. And unless its the importer of a build file is on a share filesystem, they could probably only resolve the resource with something like ipfs.

2020-05-13 17:13 UTC, astefanich commented on src/core/binary.scala
> +trait UniqueBinary {
ideas on better name, if we can't change the name of the other Binary

2020-05-13 17:13 UTC, astefanich commented on src/module/module.scala
> +    cli          <- cli.hint(BinaryRepoArg, List(RepoId("mvn_central")))
leave as central?

2020-05-13 17:16 UTC, astefanich commented on src/core/source.scala
> +  //TODO define appropriate key for jar and other resources
this key hides the absolute path. I think this plus the other resources should implement some sort of concealment, since if you give it an absolute path, it will display it. However this would affect exists builds and the parsing of keys.

2020-05-14 13:10 UTC, propensive commented
@odisseus Do you think you would be able to give @astefanich any feedback on this? I'm tied up for the next day or so... (@astefanich sorry!)

2020-05-14 14:32 UTC, odisseus commented
Okay, I'll have a look.

2020-05-15 02:58 UTC, astefanich commented
@propensive all good; no rush

2020-05-15 08:22 UTC, odisseus commented on src/core/binary.scala
> +  def apply(id: Option[BinaryId], service: BinRepoId, binSpec: BinSpec)(implicit log: Log): Try[Binary] ={
Is the log actually used in this method?

2020-05-15 12:27 UTC, odisseus commented on src/core/binary.scala
> +trait UniqueBinary {
What is the purpose of this trait?

2020-05-15 14:58 UTC, odisseus commented on src/module/module.scala
> +    cli          <- cli.hint(BinaryRepoArg, List(RepoId("mvn_central")))
The value of this argument must be either an URL of the repository (such as `https://repo1.maven.org/maven2`) or one of the standard repository names [recognized](https://get-coursier.io/docs/other-repositories) by Coursier. The name "central" corresponds to Maven Central Repository, which is a sensible default value.

2020-05-15 16:30 UTC, astefanich commented on src/core/binary.scala
> +  def apply(id: Option[BinaryId], service: BinRepoId, binSpec: BinSpec)(implicit log: Log): Try[Binary] ={
its passing implicitly in the call to paths()

2020-05-18 14:25 UTC, odisseus commented on src/core/source.scala
> +  //TODO define appropriate key for jar and other resources
I don't understand why the absolute path to a binary should be hidden. The user has a choice whether to specify the path to the binary as an absolute or a relative one. Each option has its benefits and drawbacks, and both should be supported by Fury.

2020-05-18 15:19 UTC, odisseus requested changes

2020-05-18 15:19 UTC, odisseus commented on src/core/binary.scala
> +    case _ => Failure(UnknownBinaryRepository(binRepo))
Does this mean that an attempt to use a repository other than Maven Central will fail? If so, Fury will be unable to build itself.

2020-05-18 15:19 UTC, odisseus commented on src/core/binary.scala
> +    case BinRepoId.Central => Coursier.fetch(this).recoverWith {
Use [`Try.recover`](https://www.scala-lang.org/api/2.12.10/scala/util/Try.html#recover[U%3E:T](pf:PartialFunction[Throwable,U]):scala.util.Try[U]) to avoid the need to wrap the fallback value into a Try.

2020-05-18 15:19 UTC, odisseus commented on src/core/module.scala
> +      implicit val binOrd: Ordering[UniqueBinary] = (a,b) => (a.id.key) compareTo (b.id.key)
I think [`Ordering.by`](https://www.scala-lang.org/api/2.12.10/scala/math/Ordering$.html) can be used here.

2020-05-18 15:19 UTC, odisseus commented on src/core/binary.scala
> +trait UniqueBinary {
I think this trait should be named `Binary`, and the old `Binary` should be renamed to something like `ManagedBinary`. The renaming should be done in a separate pull request though, because this one is quite large already. @propensive, what do you think about this?

2020-05-18 15:19 UTC, odisseus commented on src/core/source.scala
> +case class JarResource(id: BinaryId, repoId: RepoId, dir: Path, glob: Glob) extends Source with UniqueBinary {
Why does this class extend `Source`? The abstract class `Source` was meant to represent a directory (either local or fetched from a repository) with files that can be selected by a glob. How does a binary JAR file match this concept?

2020-05-18 15:54 UTC, astefanich commented on src/core/source.scala
> +  //TODO define appropriate key for jar and other resources
From Jon's previous post
"There's a problem with absolute paths because it makes the builds non-portable, and there's a potential security issue with someone publishing a build with a reference to /home/enemy/secrets.jar and then doing something evil with it in an application module. Something similar to the way we specify resources would allow us to choose JAR files stored inside Git repos or inside the working directory."

One can specify a binary as an absolute path or a relative one, as the full path will get resolved when one is operating inside the layer. Since its only a question of how to display the path, I was simply under the impression we shouldn't be displaying/referencing absolute paths.

2020-05-18 16:02 UTC, astefanich commented on src/core/binary.scala
> +    case _ => Failure(UnknownBinaryRepository(binRepo))
ah. will change

2020-05-18 16:30 UTC, astefanich commented
I tried to heed Jon's advice with regards to the naming and design of the binaries (not changing the existing binary, and trying to apply the resource idea to jars). 
It was mentioned in the initial issue that jars should not be able to be published unless they are contained inside a repo. This constraint has not been implemented yet, but if there is to be some intersection between jar files and repos in the future, then extending source would save some work later on, as a jar would be intersection type between the existing binary and source models.

2020-05-18 17:31 UTC, odisseus commented on src/core/source.scala
> +  //TODO define appropriate key for jar and other resources
This problem didn't occur to me. Unfortunately, forbidding references to absolute paths does not solve it at all: a malicious publisher could create a reference to `../../../../../../../../../../home/enemy/secrets.jar`, which in nearly all cases would be equivalent to an absolute path.

2020-05-18 17:58 UTC, astefanich commented on src/core/source.scala
> +  //TODO define appropriate key for jar and other resources
Agreed, my previous post mentions something like this. I don't believe its about forbidding references to absolute paths, but rather simply changing how they are displayed. The "key" value is used for JarResource effectively hides this. Even if type in an absolute path, it will only every display it with the ending file name, and conceal directories.

fury binary add -f ../../../../home/enemy/secrets.jar  
fury binary list
Id | BinRepo | Group | Artifact | Version | Path
--- | ----------- | -------- | ----------- | ----------| -------
secrets | local | - | - | - | local#file://**/secrets.jar

2020-05-19 10:44 UTC, propensive commented
@astefanich, I will try to take a good look at this later, and see if I can merge it. I'm probably about to merge a PR which will create some conflicts, but don't worry about them; I will fix them when I merge this.

2020-05-19 10:54 UTC, propensive commented on src/core/source.scala
> +case class JarResource(id: BinaryId, repoId: RepoId, dir: Path, glob: Glob) extends Source with UniqueBinary {
I think that the `Binary` type may need to be a coproduct, a bit like `Source` is, with different variants, probably something like: `RepoBinary` (for binaries stored in a linked `repo`), `LocalBinary` for local files, and `BinaryCoordinates` for references to remote Maven-style repositories. As @astefanich mentions below, I suggested trying to leave the existing `Binary` unchanged, and utilizing `Resource`s, which closely resemble `Source`s. That may still be the way to go, but I can't be sure without exploring it further. I'm not sure whether a) one approach is clearly easier than the other, b) one approach is clearly _better_ than the other, or c) whether those answers are the same.

I think my mistake was in marking this as *good first issue*. I think it's a good first issue only if you want to gain exposure to large parts of Fury's core while potentially making several wrong turns along the way... (Does that apply to you, @astefanich?) ;)

2020-05-19 15:35 UTC, astefanich commented
@propensive this was good exposure! There's probably a bit more clean up to do before merging this honestly. The "resource" entity doesn't exist, but it represented by Source, so I utilized that. I think if there's a desire to add more types like LocalBinary, RepoBinary, etc. then it would be wiser to revert back to the distinction between binaries and sources. Take a look at the output for binaries (regarding the jars "key" and how they are displayed together in the tabulation).

2020-05-19 20:50 UTC, propensive commented
Ok, sure. I'll keep trying to give feedback where I can, though we might need to make this part of a bigger set of changes if we refactor `Source`, `Resource` and `Binary`.

2020-05-27 13:58 UTC, odisseus commented on src/core/source.scala
> +  //TODO define appropriate key for jar and other resources
Perhaps I just don't understand which problem you're trying to solve. 

If you just want to hide the absolute path to a JAR when it is displayed in a table (e. g. to make the output shorter), that's just a cosmetic decision which can be easily changed later. I'm not particularly fond of the way the path looks in your example, because it looks as if it contained a glob but is not (or is it?) interpreted as a glob. But the output format can be improved later, so I'm okay with it.

If you attempt to hide the "unsafe" path to make it more "safe" while keeping the original "unsafe" one in the layer, this achieves absolutely nothing in terms of security. The "unsafe" path will be still in the layer definition, available for potential abuse by the layer creator.

If you want to rewrite the "unsafe" path into a more "safe" form and store that in the layer instead of the original path, it still doesn't achieve anything in terms of security, because relative paths  are just as unsafe as absolute ones. Moreover, it might confuse the user if the rewritten path resolves in an unexpected way under different conditions (such as another base directory or another computer).

2020-05-27 15:44 UTC, astefanich commented on src/core/source.scala
> +  //TODO define appropriate key for jar and other resources
What would be a good suggestion for concealing the path? Perhaps hashing it?
If concealment is not needed then it's not needed, but my understanding is that it is.

There just doesn't seem to a clear idea how binaries should be represented in text as well as in the model (coproduct vs "resource", remote vs local vs repo, association with git).

2020-05-27 17:16 UTC, odisseus commented on src/core/source.scala
> +  //TODO define appropriate key for jar and other resources
I believe the path should be stored in the layer as it was entered by the layer creator, without concealing anything. As for the way paths are displayed, it doesn't matter too much at the moment; you might as well keep the current way of shortening them.

2020-05-27 18:01 UTC, odisseus commented on src/core/source.scala
> +case class JarResource(id: BinaryId, repoId: RepoId, dir: Path, glob: Glob) extends Source with UniqueBinary {
Here's what I think about the binaries of different provenance and their relationship with local and repo paths.

There are just two kinds of binary. One is the "managed binary" which is downloaded from a binary repository with the help of Coursier and is identified by its "binary coordinates", i. e. its group, artifact ID, and version. The other one is the "supplied binary" which must be present in the environment when Fury runs the build; it is identified by the path at which it can be found. Support for the latter kind is the goal of #1350.

Now as for the paths that identify the "supplied binaries", these are also divided into two kinds. The first one is the plain old filesystem path; both absolute and relative paths fall into this category. The second kind is the "repo path", such as `library:src/core` ([example](https://github.com/propensive/fury/blob/master/test/passing/platform/script#L22)). In a way, these paths are both "relative" (they are mapped to different filesystem paths depending on the system environment) and "absolute" (they are resolved to the same filesystem path regardless of the command's working directory). 

Both kinds of paths are already implemented for _sources_: `LocalSource` corresponds to the filesystem path, and `ExternalSource` to the "repo path". However, these classes represent not just paths, but _source directories_, hence they also contain data unrelated to paths (namely globs).

Here are some consequences of these differences:
* If a layer refers only to "managed binaries", its build artifacts can be published to binary repositories like Maven Central or Artifactory.
* If a layer also refers to "supplied binaries" that are stored in repos, it can be published as a Fury layer. Further restrictions may apply: e. g. it probably shouldn't be published if the repo's "remote" address is just a local path.
* If a layer contains references to "supplied binaries" at filesystem path, it should not be published at all, because those paths would be unresolvable on any other filesystem. It can still be shared though.

What @propensive called a "RepoBinary" in his previous comment is basically a "supplied binary" with a "repo path", and his "LocalBinary" is my "supplied binary" with a filesystem path.

2020-11-21 12:50 UTC, closed without merging