evict old class files for correct jar artifact
propensive/fury-old pull request #1388
Opened 2020-05-17 21:58 UTC by astefanich

Old class files are being cached which is leading to incorrect jar artifacts (see my lengthy explanation regarding #1377 ). I think simply deleting a module's classes directory when sources are removed is the easiest fix. Since we only have source paths and bloop outputs to target directories, without a constraint between source paths and full qualified class names (which is as much a scala thing as it is fury), it seems virtually impossible to find and 'target delete' old class files. 
The staging directory where jars are created never gets deleted, so any class ever included in the manifest, will forever be included in a jar. Since this directory is not addressed by any of the existing clean mechanisms, simply deleting it after every jar creation does the trick.

2020-05-18 12:36 UTC, odisseus requested changes
Good job, but the integration test can be improved a little bit.

2020-05-18 12:36 UTC, odisseus commented on test/passing/class-eviction/script
> +fury build run -F -f out --output quiet | awk '{print $1}'
Don't discard the output unless it contains variable parts, such as absolute paths or commit hashes. Even then, you should try to discard as little as possible, ideally just the variable part. Changes in the incidental output (e. g. size of the created JAR file) sometimes help spot unexpected problems.

2020-05-18 12:36 UTC, odisseus commented on test/passing/class-eviction/script
> +jar -tf out/cache-test-my-module.jar | grep LibA
If you remove the `-F` flag from the build commands, you won't have to filter out the standard library classes from the archive listing, and the grep pipe will become unnecessary.

2020-05-19 00:12 UTC, odisseus commented on src/core/policy.scala
> +      Privilege(GlobalScope, Permission(ClassRef("java.lang.reflect.ReflectPermission"), "suppressAccessChecks", None)),
Why?

2020-05-19 00:13 UTC, odisseus commented on test/passing/scala3/script
> -fury permission require -C java.lang.RuntimePermission -T accessClassInPackage.sun.misc
Is this related to the issue with stale source and class files?

2020-05-19 00:17 UTC, merged

2020-05-19 14:52 UTC, astefanich commented
closes #1377