Improve binary handling
propensive/fury-old pull request #1504
Opened 2020-08-09 16:08 UTC by propensive

2020-08-17 03:43 UTC, odisseus requested changes
Can the introduction of workspaces, Docker images etc. be separated from the changes to Coursier interaction?

By the way, the unit tests fail with [compilation errors](https://github.com/propensive/fury/runs/990675652?check_suite_focus=true#step:7:114):
```
 51.054 [E] fury/text-test>local:src/text-test/prefixes.scala:27:26
 51.054 | not found: type Suite
 51.054 | object TextTests extends Suite() {
 51.155 Compilation of module fury/text-test failed
```

2020-08-17 03:43 UTC, odisseus commented on src/compile/compile.scala
> +        /*glob(layout.workDir(include.ref), layout.workDir(include.ref).walkTree).traverse { p =>
Why?

2020-08-17 03:43 UTC, odisseus commented on src/core/cli.scala
> +  def boolean(arg: CliParam): Try[Boolean] = opt(arg).map(_.isDefined)
How is this going to be using in practice? Do I understand correctly that this method should return `Success(true)` e.g. when the user types `--gzip on` and `Success(false)` when the user types `--gzip off`?

2020-08-17 03:43 UTC, odisseus commented on src/core/cli.scala
> +  object sourceHints {
Are these hinters useful anywhere outside `SourceCli`?

2020-08-17 03:43 UTC, odisseus commented on src/core/shell.scala
> +    def images(): Try[List[ImageId]] = sh"".exec[Try[String]].map { str =>
The actual shell command is missing.

2020-08-17 03:43 UTC, odisseus commented on src/frontend/recovery.scala
> +          log.info("This module contains conflicting binaries.")
The error message would be more clear if it included the name of the affected module.

2020-08-17 03:43 UTC, odisseus commented on src/model/ids.scala
> +    case r"[_a-zA-Z0-9][_.\-a-zA-Z0-9]*[_a-zA-Z0-9]" => ImageId(str)
The list `[_a-zA-Z0-9]` is equivalent to `\w`. See #1486.

2020-08-17 03:43 UTC, odisseus commented on src/model/kinds.scala
> +sealed abstract class Kind(val needsExec: Boolean = false) extends scala.Product with scala.Serializable {
Why?

2020-08-26 06:08 UTC, propensive commented on src/compile/compile.scala
> +        /*glob(layout.workDir(include.ref), layout.workDir(include.ref).walkTree).traverse { p =>
I can't remember... but it looks like something I'll need to sort out when I get there.

2020-08-26 06:10 UTC, propensive commented on src/core/cli.scala
> +  def boolean(arg: CliParam): Try[Boolean] = opt(arg).map(_.isDefined)
It's intended for "present"/"not present" checking, for parameters that are parameterized on `Unit`. IIRC, it converts them from `Success(())` to `Success(true)` and `Failure(_)` to `Success(false)`.

2020-08-26 06:11 UTC, propensive commented on src/core/cli.scala
> +  object sourceHints {
Potentially... I think there are actually references to them from two different files, though I don't remember which.

2020-08-26 06:12 UTC, propensive commented on src/core/shell.scala
> +    def images(): Try[List[ImageId]] = sh"".exec[Try[String]].map { str =>
Thanks - I think I was actually confused why I wasn't getting Docker image suggestions...

2020-08-26 06:13 UTC, propensive commented on src/frontend/recovery.scala
> +          log.info("This module contains conflicting binaries.")
There is _lots_ more information we could show here, including strategies for fixing the problem.

2020-08-26 06:14 UTC, propensive commented on src/model/kinds.scala
> +sealed abstract class Kind(val needsExec: Boolean = false) extends scala.Product with scala.Serializable {
This has the effect that the inferred LUB of two or more of `Kind`'s subtypes will be `Kind` rather than `Kind with Product with Serializable`. It makes some errors nicer.

2020-08-26 06:15 UTC, propensive commented on src/model/ids.scala
> +    case r"[_a-zA-Z0-9][_.\-a-zA-Z0-9]*[_a-zA-Z0-9]" => ImageId(str)
I'll change it. I can never remember all these character classess...

2020-12-10 19:53 UTC, closed without merging