verify modules before compiling or publishing
propensive/fury-old pull request #203
Opened 2019-01-25 10:26 UTC by marek1840

closes #26

2019-01-25 10:40 UTC, propensive requested changes

2019-01-25 10:40 UTC, propensive commented on src/build/build.scala
> +      _             <- Verifier.verifyUniverse(universe)
This isn't quite necessary. We only need to verify all the modules in all the projects in all the schemas in the current layer. We don't need to verify the entire universe. But we do need the universe to check that the references resolve.

2019-01-25 10:40 UTC, propensive commented on src/core/fury/module/Verifier.scala
> +      schema  <- universe.schemas.values
So this should be just `layer.schemas`.

2019-01-25 10:40 UTC, propensive commented on src/core/fury/module/Verifier.scala
> +    definedModules.foldLeft(~Set[ModuleId]()) {
This fold is fine, but a recursive definition might be easier to work with. No need to change it.

2019-01-25 10:40 UTC, propensive commented on src/core/fury/module/Verifier.scala
> +  def verifyModule(universe: Universe, module: Module): Outcome[Set[ModuleId]] =
I think this is more complicated than it needs to be. Don't worry - that's a good thing. Here's some pseudocode for what we need to do
```
for {
  schema <- layer.schemas
  project <- schema.projects
  module <- project.modules
  dep <- module.dependencies + module.compiler
 } yield universe.projects(dep.projectId).contains(dep.moduleId)
```

Then make this into a fold or a recursive method.

2019-11-22 15:30 UTC, odisseus commented
This pull request has become unmergeable..

2019-11-22 15:30 UTC, closed without merging