Ensure that layers are always migrated to latest version
propensive/fury-old pull request #242
Opened 2019-02-09 13:07 UTC by propensive

2019-02-09 14:30 UTC, mzarnowski requested changes

2019-02-09 14:30 UTC, marek1840 commented on src/core/data.scala
> +    LayerRepository(layout).update(io, layer, layout)
`io` is a construction time dependency. If you feel you have to propagate it - do it using the constructor ;)

2019-02-09 15:13 UTC, propensive commented on src/core/data.scala
> +    LayerRepository(layout).update(io, layer, layout)
`Io` is inherently impure, though, so we should never be "storing" it in an object, should we?

2019-02-09 15:48 UTC, marek1840 commented on src/core/data.scala
> +    LayerRepository(layout).update(io, layer, layout)
It is just a dependency and if it never changes across within single runtime it can be safely stored in an object to reduce the clutter :)
Also the layer repository does not leave the scope of "save", so it is not passed anywhere it should not be :)

2019-02-10 07:32 UTC, propensive commented on src/core/data.scala
> +    LayerRepository(layout).update(io, layer, layout)
So it's fine in this case, but I don't like the principle of it: That `Io` object contains a reference to `stdout`, and we would be including an opaque reference to it. We could quite easily make a change like adding caching to `LayerRepository` later on, and it wouldn't be clear that we would have an implicit reference to a particular `stdout`. So I don't want to do this. By the way, I'd probably feel different if `LayerRepository` were a method-local class, but I find it much easier to follow the rule that we don't store `Io`s on-heap.

The same applies to `Layout` because it includes a reference to the current directory, and it's generally why these methods are passed around everywhere. There might be an opportunity to combine the `Io` and `Layout` types, but there are disadvantages to that too.

2019-02-10 09:52 UTC, merged