Use BSP instead of calling bloop via CLI
propensive/fury-old pull request #278
Opened 2019-03-04 16:40 UTC by tpasternak

Known limiations that will be fixed in future:

1. New BSP connection is established and destroyed each time, what is not optimal.
2. Build progress messages are unused
3. Error messages should be more human-friendly
4. After BSP "buildTargetCompile" module is called, the
"workspaceBuildTargets" request is sent. Without it, bloop sometimes hang.

2019-03-07 20:56 UTC, jastice commented
I've talked to @jvican about releasing a breaking update to the BSP library in prepraration for BSP 2.0. We should have it available by monday morning to build against.

2019-03-08 12:12 UTC, jvican requested changes
I'm excited about this! :tada: Great work :rocket:
  
 I just have an important comment regarding how you should connect to the server. See https://scalacenter.github.io/bloop/docs/launcher-reference.html for more information

> I've talked to @jvican about releasing a breaking update to the BSP library in prepraration for BSP 2.0. We should have it available by monday morning to build against.
  
Confirmed.

2019-03-08 12:12 UTC, jvican commented on src/core/data.scala
> +    val furyTempPath = Path.getTempDir("fury-socket-").get
It is strongly encouraged to use the bloop launcher instead of creating your own logic to connect to the server. Otherwise, I cannot ensure that connections will always work and I'm forced upstream to break clients (because the connection mechanisms may change over time).

2019-03-11 15:18 UTC, tpasternak commented on src/core/data.scala
> +    val furyTempPath = Path.getTempDir("fury-socket-").get
We wanted to do it (also for performance reasons) but I think this can be done as the next step. The approach where we create&destroy BSP sessions each time is just simpler to implement

2019-03-11 15:19 UTC, merged

2019-03-12 00:09 UTC, jvican commented on src/core/data.scala
> +    val furyTempPath = Path.getTempDir("fury-socket-").get
Why is performance relevant here? The launcher does a lot of things (starting server if it isn't there, working in cross-platform, starting an embedded mode, etc) so I want to make sure all clients are all in on using it and don't use custom logic to connect to the server.

2019-03-12 08:41 UTC, tpasternak commented on src/core/data.scala
> +    val furyTempPath = Path.getTempDir("fury-socket-").get
Oh, I just meant we _will_ achieve better performance after switch to launcher and use a single launcher std i/o session, instead of creation/destruction of bsp sessions each time :)

2019-03-12 11:52 UTC, jvican commented on src/core/data.scala
> +    val furyTempPath = Path.getTempDir("fury-socket-").get
Sounds good, let me know if you have any questions!