Added a test for concurrent borrowing of resources.
propensive/fury-old pull request #493
Opened 2019-08-23 11:57 UTC by odisseus

2019-09-03 15:18 UTC, mzarnowski requested changes
The test looks sound. There is a rouge `println` in there, so after removing it, the PR can be merged if this is urgent, as other comments are purely cosmetic.

2019-09-03 15:18 UTC, marek1840 commented on src/core-test/testpool.scala
> +      val keys = "klmnop".toSeq.map(c => s"a/b/$c")
if the string `klmnop` stands for something meaningful, please extract it to a variable to avoid confusion.
If it does not - can you use something like "abcdef" or "uvwxyz"? Maybe the latter, since it doesn't look like anything on the first glance?

2019-09-03 15:18 UTC, marek1840 commented on src/core-test/testpool.scala
> +      override def isBad(value: Resource): Boolean = false
does `isBad` mean `isInvalid`? Or something entirely different?

2019-09-03 15:18 UTC, marek1840 commented on src/core-test/testpool.scala
> +      allFinished.await()
is there a time limit somewhere, so that this test doesn't hang on failure?

2019-09-03 15:18 UTC, marek1840 commented on src/core-test/testpool.scala
> +      println(dummyPool.size)
```suggestion
```

2019-09-03 15:18 UTC, marek1840 commented on src/core-test/testpool.scala
> +      dummyPool.size
it would be more expressive to have:
```scala
  (...)
  allFinished.await()
  dummyPool
}.assert(_.size == 6)
...

2019-09-03 15:18 UTC, marek1840 commented on src/core-test/testpool.scala
> +      val keys = "klmnop".toSeq.map(c => s"a/b/$c")
do those `/` matter? if not, maybe we could use `UUID.randomUUID`  to convey the lack of inherent meaning of the keys?

2019-09-03 15:18 UTC, marek1840 commented on src/core-test/testpool.scala
> +      (result1.tag, result2.tag, result3.tag)
```suggestion
      (result1, result2, result3).map(_.tag)
```

2019-09-03 15:20 UTC, marek1840 commented on src/core-test/testpool.scala
> +          dummyPool.borrow(key){void}
this takes ownership and immediately returns it, right? 
Would the semantic hold, if the `Thread.sleep(100)` was moved in the place of `void` ?

2019-09-04 09:48 UTC, odisseus commented on src/core-test/testpool.scala
> +      val keys = "klmnop".toSeq.map(c => s"a/b/$c")
Okay, if you really think that "uvwxyz" is more (or less?) meaningful than "klmnop"...

2019-09-04 09:50 UTC, odisseus commented on src/core-test/testpool.scala
> +      override def isBad(value: Resource): Boolean = false
It just means that the resource cannot be used anymore, whatever the cause might be.

2019-09-04 09:59 UTC, odisseus commented on src/core-test/testpool.scala
> +      allFinished.await()
Yes, the unit tests would eventually [time out](https://github.com/propensive/fury/blob/master/cloudbuild.yaml#L14).

2019-09-04 09:59 UTC, odisseus commented on src/core-test/testpool.scala
> +      println(dummyPool.size)
Ok

2019-09-04 10:00 UTC, odisseus commented on src/core-test/testpool.scala
> +      dummyPool.size
Does it really make a difference?

2019-09-04 10:03 UTC, odisseus commented on src/core-test/testpool.scala
> +      val keys = "klmnop".toSeq.map(c => s"a/b/$c")
UUIDs are hard to compare visually. Besides, when the pool is used for storing BSP connections, the keys very much have meaning; they are paths to the corresponding working directories.

2019-09-04 10:06 UTC, odisseus commented on src/core-test/testpool.scala
> +      (result1.tag, result2.tag, result3.tag)
Would this even compile?

2019-09-04 10:08 UTC, odisseus commented on src/core-test/testpool.scala
> +          dummyPool.borrow(key){void}
It should have been there all along.

2019-09-04 10:18 UTC, marek1840 commented on src/core-test/testpool.scala
> +      dummyPool.size
semantically? no.

but with this change you don't have to look on the above line to know what is being compared with zero. I think the easier it is to reason about a piece of code, the better it is.

ideally it should be `pool.size == 0` but that is more boilerplatish with `probably`

2019-09-04 10:23 UTC, marek1840 commented on src/core-test/testpool.scala
> +      val keys = "klmnop".toSeq.map(c => s"a/b/$c")
OK, I agree UUID might be a bad choice here.

If I understand correctly, the pool itself doesn't care about the meaning of the keys, right? If so, the tests should also be as simple as possible. If the sequence `('a' to 'z').map(i => s"key $i")` works, then it should be used **unless** the test itself depend on the form of the key.

2019-09-04 10:24 UTC, marek1840 commented on src/core-test/testpool.scala
> +      (result1.tag, result2.tag, result3.tag)
right, that is not a list but a tuple... nevermind then

2019-09-04 10:26 UTC, marek1840 commented on src/core-test/testpool.scala
> +      override def isBad(value: Resource): Boolean = false
so, basically, another word for `invalid` ;)

2019-09-04 10:27 UTC, marek1840 commented on src/core-test/testpool.scala
> +      val keys = "klmnop".toSeq.map(c => s"a/b/$c")
when replying to the comment below, I noticed that what really would be nicer is: `('k' to 'p')` ;)

2019-09-04 12:46 UTC, odisseus commented on src/core-test/testpool.scala
> +      val keys = "klmnop".toSeq.map(c => s"a/b/$c")
Ok

2019-09-04 13:00 UTC, odisseus commented on src/core-test/testpool.scala
> +      dummyPool.size
Ok

2019-09-04 14:08 UTC, odisseus commented on src/core-test/testpool.scala
> +      val keys = "klmnop".toSeq.map(c => s"a/b/$c")
Ok

2019-09-04 16:54 UTC, closed without merging