wip
propensive/fury-old pull request #504
Opened 2019-09-03 12:50 UTC by odisseus

2019-09-03 15:31 UTC, mzarnowski requested changes
Using iterator sounds like a good idea.
There are minor things which can be improved before merging.

2019-09-03 15:31 UTC, marek1840 commented on src/core/graph.scala
> +      val foo = compilationLogs.updated(ref, f(previousState))
rename `foo`  Maybe `updatedState` ?

2019-09-03 15:31 UTC, marek1840 commented on src/core/graph.scala
> +      stream.next match {
`live` is repeated at the end of every branch, maybe it could be extracted?
```scala
val foo = stream.next match { 
  (...)
}
live(foo)

2019-09-03 15:31 UTC, marek1840 commented on src/core/graph.scala
> +          val newState = CompilationInfo(if (success) Successful(None) else Failed(""), msgs)
what does the `Failed("")` mean and where (if anywhere) would the user see an empty string?

2019-09-04 09:22 UTC, odisseus commented on src/core/graph.scala
> +      val foo = compilationLogs.updated(ref, f(previousState))
I'll just inline it.

2019-09-04 09:35 UTC, odisseus commented on src/core/graph.scala
> +      stream.next match {
Ok

2019-09-04 09:43 UTC, odisseus commented on src/core/graph.scala
> +          val newState = CompilationInfo(if (success) Successful(None) else Failed(""), msgs)
This is a token that makes the graph printer [print](https://github.com/propensive/fury/blob/master/src/core/graph.scala#L154) "_x_ errors". Its field is just ignored.

2019-09-04 10:15 UTC, mzarnowski approved these changes

2019-09-04 10:24 UTC, merged