Refactored some recursive methods to tail recursion.
propensive/fury-old pull request #532
Opened 2019-09-23 12:32 UTC by odisseus

2019-09-24 10:19 UTC, mzarnowski requested changes

2019-09-24 10:19 UTC, marek1840 commented on src/core/data.scala
> +      if(next.isEmpty) ~aggregated
1. is the `ch.get` an optimization? Why not use a match instead?
2. `children` parameter can be renamed  to `extract` to reflect its purpose
3. `next` could also be renamed to `sources` for the same reason.
4. Do we need to append it on the end? `:+` rebuilds the collection every time. Could we append the node at the beginning with and then, if the needs be, reverse the result of `flatten` in line 945?
5. can a schema be imported only from one source? Wouldn't this result in duplication of schemas if, for example, A and B import the same schema C?

Here is a proposal:


```scala
def flatten[T](acc: List[T], extract: T => Try[List[T]], sources: List[T]): Try[List[T]] = {
  sources match {
    case Nil =>  ~acc
    case source :: tail =>
      extract(source) match {
        case Success(children) =>
          flatten(head :: acc, children, tail ++ children)
        case failure =>
          failure
   }
}
```

2019-09-24 10:19 UTC, marek1840 commented on src/core/data.scala
> +      allSchemas <- flatten[Schema] (Nil, _.importedSchemas(io, layout, https), List(this))
by making the flatten:
```scala
def flatten[A](sources: List[A])(acc: List[A], extract: A => Try[List[A]]): Try[List[A]] = ???
```

we could probably use it here like this:
```scala
for {
  allSchemas <- flatten(List(this))(Nil, _.importedSchemas(io, layout, https))
}
```
which doesn't require specifying a type

2019-09-24 10:19 UTC, marek1840 commented on src/io/path.scala
> +  def empty: Boolean = Files.walk(javaPath).allMatch(p => Files.isDirectory(p))
`Files.walk` (and `list`) returns a stream which must be closed after consuming it.
```scala
val stream = Files.walk(javaPath)
try stream.allMatch(p => Files.isDirectory(p))
finally stream.close()
```

2019-09-24 14:44 UTC, odisseus commented on src/io/path.scala
> +  def empty: Boolean = Files.walk(javaPath).allMatch(p => Files.isDirectory(p))
I'm not sure that's [necessary](https://stackoverflow.com/a/38698245), but let's be on the safe side.

2019-09-24 14:49 UTC, odisseus commented on src/io/path.scala
> +  def empty: Boolean = Files.walk(javaPath).allMatch(p => Files.isDirectory(p))
Ok

2019-09-24 22:09 UTC, odisseus commented on src/core/data.scala
> +      allSchemas <- flatten[Schema] (Nil, _.importedSchemas(io, layout, https), List(this))
Ok

2019-09-24 22:31 UTC, odisseus commented on src/core/data.scala
> +      if(next.isEmpty) ~aggregated
Refactored

2019-09-25 09:08 UTC, propensive approved these changes

2019-09-25 09:08 UTC, merged