Add module param to binary add command
propensive/fury-old pull request #633
Opened 2019-10-22 09:07 UTC by IvoSaraiva

The -m option was being supplied in a cli that was not being used neither in the BinariesCtx nor the ParamCtx. Moved it to the ModuleCli.context. 

This should fix #260 for binaries and also for params.

2019-10-22 23:57 UTC, odisseus requested changes

2019-10-22 23:57 UTC, odisseus commented on src/module/module.scala
> +    cli          <- cli.hint(ModuleArg, optProject.to[List].flatMap(_.modules))
If this is the right place to generate a hint for the `--module` argument, the value associated with this argument should also be retrieved here, like it is done with `--schema` and `--project`. Consider adding `optModule` as another field to the case class `ModuleCli.Context`.

By the way, doesn't this change enable the hint for `--module` argument even for commands `module add` and `module list`? These two commands don't (and shouldn't) accept that argument.

2019-10-23 14:22 UTC, IvoSaraiva commented on src/module/module.scala
> +    cli          <- cli.hint(ModuleArg, optProject.to[List].flatMap(_.modules))
You're right on the module commands problem. I'll try again.

2019-10-23 14:47 UTC, IvoSaraiva commented
What about just updating the MoculeCli.Context.cli in the BinariesCtx and ParamCtx? All binaries and params commands should accept a --module option.

2019-10-24 11:21 UTC, propensive approved these changes

2019-11-08 16:24 UTC, odisseus commented
I'm OK with merging this if @propensive approves.

2019-11-13 04:44 UTC, merged

2019-11-13 04:44 UTC, propensive commented
Yes, I just tried it out, and it works great. Nice that the fix was so simple!