Bug/Good First Issue/Backend
propensive/fury-old pull request #655
Opened 2019-11-08 16:00 UTC by ricardoffmartins

failure to pull one repository aborts updating others #329

Created two Fury Exceptions

Added two TODO's for message specification.

2019-11-08 16:20 UTC, odisseus requested changes

2019-11-08 16:20 UTC, odisseus commented on src/core/data.scala
> +    commit <- Shell(layout.env).git.getCommit(dir,repo.path(layout).name)
Please add a whitespace after the comma.

2019-11-08 16:20 UTC, odisseus commented on src/core/data.scala
> +      Success(msg"Unable to get commit identifier for repo $repo.")
Instead of mapping `Failure` to `Success`, add new case clauses in the file [`recovery.scala`](https://github.com/propensive/fury/blob/master/src/frontend/recovery.scala). 

For an example, see how `OgdlException` is used.

2019-11-09 15:43 UTC, propensive requested changes

2019-11-09 15:43 UTC, propensive commented on src/core/shell.scala
> +      sh"git -C ${dir.value} rev-parse --short HEAD".exec[Try[String]] match {
Use the `Try#recoverWith` method instead, here.

2019-11-09 15:43 UTC, propensive commented on src/core/data.scala
> +      Success(msg"Unable to get commit identifier for repo $repo.")
I'm not sure, but I think the intent of mapping it to a success was so that when several `update`s are chained together, they continue. But this isn't the right approach. There will be a `fold` or a `sequence` which maps `update` over a list of repositories, somewhere, and I think that's where the problem is. The `update` method should still return a `Failure` if it fails, but we shouldn't be `fold`ing them together.

2019-11-11 11:55 UTC, ricardoffmartins commented on src/core/data.scala
> +      Success(msg"Unable to get commit identifier for repo $repo.")
Yes, that is correct, the idea is for it not to stop the entire process. And return some info about which component failed.
@propensive 
"There will be a **fold** or a **sequence**..."
I can see this line 
   _msgs      <- repos.map(_.repo.update(layout).map(io.println(_))).sequence_
in the  pull method, this sequence comes from another project named mercator, if i'm not mistaken, please correct me if i'm wrong. 
Is this sequence that we should take into account not to fold the Failures with the Success???

2019-11-12 06:44 UTC, odisseus commented on src/core/data.scala
> +      Success(msg"Unable to get commit identifier for repo $repo.")
Yes, this is where a `Set[Try[_]]` is [converted](https://github.com/propensive/mercator/blob/master/core/shared/src/main/scala-2.12/compat.scala#L7) into `Try[Set[_]]`. As a result, the whole set of operations is converted into a `Failure` if a single operation fails.

2020-04-05 19:22 UTC, closed without merging