Added tests for parsing identifiers of various entities.
propensive/fury-old pull request #920
Opened 2020-01-10 17:43 UTC by odisseus

2020-01-11 10:50 UTC, propensive requested changes

2020-01-11 10:50 UTC, propensive commented on src/model-test/idtests.scala
> +      BinaryId.unapply("baz-quux_2.12").isDefined
I think that this shouldn't actually be a valid ID. The purpose of the ID is not to encode a version number, and it should be actively discouraged. I'll need to update the code which infers a `BinaryId` from a `BinSpec`, though.

@odisseus Can you update the tests to reflect this? I'll update the method in a separate PR.

2020-01-13 11:55 UTC, odisseus commented on src/model-test/idtests.scala
> +      BinaryId.unapply("baz-quux_2.12").isDefined
Ok

2020-01-17 10:54 UTC, propensive commented
Can this be marked "Ready for review" yet?

2020-01-17 10:59 UTC, odisseus commented
This pull request can be safely merged now, but I was going to add some more tests before merging.

2020-01-20 09:48 UTC, merged