Write BSP trace to file
propensive/fury-old pull request #942
Opened 2020-01-16 14:58 UTC by odisseus

These changes obviously aren't ready to be merged yet, but they may already be useful for debugging.

2020-01-17 10:41 UTC, propensive commented on src/build/build.scala
> +                                bspTrace: Option[Path])
See my comment on the issue, but I think that logging to the global log should be the only option. My reasoning is that if we follow this example, we could end up offering different log files for every external program we integrate with, and I don't want to go down that route. We already have a global log, and we can use that to interleave BSP output with other things that Fury is doing, in chronological order.

2020-01-17 10:42 UTC, propensive commented on src/compile/compile.scala
> +    //FIXME a connection will inherit the trace destination (or lack thereof) from its first usage
This would be fixed by using the global log.

2020-01-17 10:43 UTC, propensive commented on src/core/args.scala
> +  val TraceArg = CliParam[Path]('t', Symbol("bsp-trace"), "Write the BSP communication trace to a file")
Make it a `CliParam[Unit]` to make it a flag.

2020-01-17 10:44 UTC, propensive requested changes
I think we should simplify this to use the global log.

2020-01-17 11:11 UTC, odisseus commented on src/build/build.scala
> +                                bspTrace: Option[Path])
The BSP trace is different from logs generated by Fury. I agree that it is convenient to seethe exact chronological order of all events that happened, but intermingling BSP traces with the logs would make both very hard to read.

The BSP server is quite different from other external programs, because it is by far the most tightly integrated and has the most complex interaction with Fury. I think it is reasonable to make an exception and write its traces into a separate file, because these aren't just another kind of Fury logs. It won't make a big impact on the typical user, because by default the traces would not be written at all.

2020-01-17 14:07 UTC, odisseus commented on src/compile/compile.scala
> +    //FIXME a connection will inherit the trace destination (or lack thereof) from its first usage
I resolved this problem by making the configuration global.

2020-01-17 14:38 UTC, propensive reviewed
Can we do it without the new dependency?

2020-01-17 14:42 UTC, odisseus commented on src/core/args.scala
> +  val TraceArg = CliParam[Path]('t', Symbol("bsp-trace"), "Write the BSP communication trace to a file")
This parameter has to be boolean now, so that the user can set the configuration property to true or false.

2020-01-17 14:51 UTC, odisseus commented
Looks like it is quite feasible. The easiest way would be copying the source code of [Apache's `TeeOutputStream`](https://github.com/apache/commons-io/blob/b8f638fa691dc600248b9d810927d0491a46bc0f/src/main/java/org/apache/commons/io/output/TeeOutputStream.java).

2020-01-18 09:33 UTC, propensive commented
I think we can probably implement the relevant parts of the `TeeOutputStream` in just a few lines of Scala. I'll have a go later, then I think this is ready to merge.

2020-01-18 23:23 UTC, odisseus commented
Done

2020-01-19 01:43 UTC, merged